"""Tests for FSTO/1 contract conformance."""

import pytest
from fsto1 import generate_canonical, get_canonical_hex, get_canonical_digest


# Expected canonical values (independently stored, not generated)
EXPECTED_CANONICAL_RECORD = (
    b"devid=FW-TEACHING-01 eventtime=1672531200000000000 logid=0000000013 "
    b"type=traffic subtype=forward action=close proto=6 srcip=192.0.2.10 "
    b"dstip=198.51.100.20 dstport=443 sentbyte=4096"
)

EXPECTED_LENGTH = 180

EXPECTED_SHA256 = "62bf0871bd1148b2c1f1afbe3a500740d5a936af5d1dec3b724ab1c85486a653"

EXPECTED_HEX = (
    "6465766964"
    "3d46572d544541"
    "4348494e472d30312065"
    "76656e7474696d653d31363732353331323030303030303030303030206c6f676964"
    "3d30303030303030303133207479"
    "70653d747261666669632073756274"
    "7970653d666f727761726420616374696f6e3d636c6f73652070726f746f3d362073"
    "726369703d3139322e302e322e3130206473746970"
    "3d3139382e35312e3130302e3230206473"
    "74706f72743d34343320"
    "73656e74627974653d34303936"
)


def test_canonical_length():
    """Generated record must be exactly 180 bytes."""
    record = generate_canonical()
    assert len(record) == EXPECTED_LENGTH


def test_canonical_golden_bytes():
    """Generated bytes must match the canonical record exactly.

    This is the golden-byte test. It compares generated bytes against
    an independently stored expected value (not through the same code path).
    """
    record = generate_canonical()
    assert record == EXPECTED_CANONICAL_RECORD


def test_canonical_sha256():
    """Generated record SHA-256 must match expected digest."""
    digest = get_canonical_digest()
    assert digest == EXPECTED_SHA256


def test_canonical_hex():
    """Generated record hex must match expected representation."""
    hex_repr = get_canonical_hex()
    assert hex_repr == EXPECTED_HEX


def test_deterministic_generation():
    """Multiple calls must produce identical bytes."""
    record1 = generate_canonical()
    record2 = generate_canonical()
    record3 = generate_canonical()

    assert record1 == record2 == record3


def test_utf8_encoding():
    """Record must be valid UTF-8."""
    record = generate_canonical()
    # Should decode without error
    decoded = record.decode('utf-8')
    assert isinstance(decoded, str)
    # Should re-encode to same bytes
    assert decoded.encode('utf-8') == record


def test_no_newline_terminator():
    """Record must not end with newline, CR, or NUL."""
    record = generate_canonical()
    assert not record.endswith(b'\n')
    assert not record.endswith(b'\r')
    assert not record.endswith(b'\x00')
    assert not record.endswith(b'\r\n')


def test_no_bom():
    """Record must not start with UTF-8 BOM."""
    record = generate_canonical()
    assert not record.startswith(b'\xef\xbb\xbf')


def test_printable_ascii():
    """All bytes must be printable ASCII (0x20-0x7E) except spaces as delimiters."""
    record = generate_canonical()
    for byte in record:
        assert 0x20 <= byte <= 0x7E, f"Non-printable byte: 0x{byte:02x}"


def test_field_structure():
    """Record must contain all eleven fields in documented order."""
    record = generate_canonical().decode('utf-8')

    # Must contain all field names
    expected_fields = [
        'devid=', 'eventtime=', 'logid=', 'type=', 'subtype=',
        'action=', 'proto=', 'srcip=', 'dstip=', 'dstport=', 'sentbyte='
    ]

    for field in expected_fields:
        assert field in record, f"Missing field: {field}"

    # Fields must appear in order
    parts = record.split(' ')
    assert len(parts) == 11

    assert parts[0].startswith('devid=')
    assert parts[1].startswith('eventtime=')
    assert parts[2].startswith('logid=')
    assert parts[3].startswith('type=')
    assert parts[4].startswith('subtype=')
    assert parts[5].startswith('action=')
    assert parts[6].startswith('proto=')
    assert parts[7].startswith('srcip=')
    assert parts[8].startswith('dstip=')
    assert parts[9].startswith('dstport=')
    assert parts[10].startswith('sentbyte=')


def test_no_contract_version_in_payload():
    """Contract version must not be embedded in the source-shaped payload."""
    record = generate_canonical().decode('utf-8')
    assert 'FSTO' not in record
    assert 'contract' not in record.lower()
    assert 'version' not in record.lower()
